### ISSUE TITLE
How to select topic?

### ISSUE THREAD

**Issue by YGD159** [eProsima/plotjuggler-fastdds-plugins#47]
I want to use this visualizer, but it can't select topic.
Could you give me some good advice, millions of thanks.
![2022-11-14 17-45-11屏幕截图](https://user-images.githubusercontent.com/52145923/201628403-5db13928-1502-4b4f-b9a8-67d7bb7a01f6.png)

**Comment by YGD159** [comment]
I install it by using this program  named eProsima_PlotJuggler-eProsima-Edition-v1.0.0-Linux.run
https://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-dds-visualizer/eprosima-fast-dds-visualizer-1-0-0

**Comment by YGD159** [comment]
![2022-11-14 18-49-36屏幕截图](https://user-images.githubusercontent.com/52145923/201641658-95ac355a-55da-4973-b047-0da0d4ceeab1.png)
![2022-11-14 18-49-45屏幕截图](https://user-images.githubusercontent.com/52145923/201641664-77494ea2-bd66-45ec-abb3-d38a60e3a231.png)

**Comment by jparisu** [comment]
Hi @YGD159 

The main reason the topic is not selectable is because the Fast DDS underneath the plugin does not know this Data Type. As it is said in the documentation `Be aware that some data types may not be known by the internal Fast DDS application, and must be discovered via Dynamic Types.` https://plotjuggler-fastdds-plugins.readthedocs.io/en/latest/rst/user_manual/configuration.html#select-topics

Also, there is no support for `.idl` files in this plugin.
The simplest way to achieve it is by an `.xml` description file, as it is explained in this documentation page: https://plotjuggler-fastdds-plugins.readthedocs.io/en/latest/rst/user_manual/dynamic_data_types.html#xml-data-type

However, I could not assure you the correct behaviour of it as a known bug in Fast DDS limits the use of Data Types, and yours is not correctly supported (it is specified in a warning in the documentation page I linked before).
Try to use other Data Type, as a bounded array or a string to define your Type.

**Comment by YGD159** [comment]
Thank you for your reply, looking forward to update the tool in the future.

**Comment by nlw0** [comment]
> Also, there is no support for `.idl` files in this plugin. The simplest way to achieve it is by an `.xml` description file, as it is explained in this documentation page: https://plotjuggler-fastdds-plugins.readthedocs.io/en/latest/rst/user_manual/dynamic_data_types.html#xml-data-type

Hope it's OK if I reply to this closed issue. I'm trying to start using Fast DDS. I was able to run the hello_world example, the shapes example, and I was able to get Fast DDS Visualizer running. I was also able to see the shapes data in the visualizer, but not the hello_world data. I can see the topic in the list, and click on it, and I added the xml file for the helloworld struct as in the example, but I still cannot select any values to visualize. I suppose we should be able to visualize the counter there. What's missing?
